### PR TITLE
feat:  update verida packages

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Updated verida packages
- Updated user profile avatar
- Updated schema URL

### CODE REVIEW

**Comment by nick-verida** [comment]
image

There seems to be a few issues if the avatar isn't defined. This error is showing when the user is logged out.

**Comment by nick-verida** [comment]
And if I log in with an account that **has no avatar** I get this (that avatar was from a different account!!)

image

**Review by nick-verida — CHANGES_REQUESTED** [review]
Changes needs, as comments

**Comment by cmcWebCode40** [comment]
@nick-verida, this issue has been fixed, I have tested with the most recent version of the vault `0.2.2(1)`

**Comment by nick-verida** [comment]
* Log in with a profile with an avatar
* Log out
* Log in with a profile without an Avatar
* See the previous log in's avatar.

In this image N24 doe *NOT* have an avatar. 

image

Note that this is exactly the same issue outlined here: https://github.com/verida/tech-capabilities-demo/pull/58#issuecomment-971174218

**Review by nick-verida — APPROVED** [review]
Working!

Merging

**Pull request merged**
