### PR TITLE
Feature/demo fixes

### LINKED ISSUE #35: Issues with forward/back nav between demos
The forward/back nav needs a few fixes:
* Remove the blank image holders
* Make the whole text work as a link (not just the arrows)
* Titles should be "Previous Demo" (not PreviousDemo) and "Next Demo" (not CurrentDemo)
* Some of the links to the next and previous demos are incorrect. 
* The first demo should only link to the next one. The link should be centered on the page
* The final demo should only link to the previous one. The link should be centered on the page

image

### PR DESCRIPTION
**Pull request by cmcWebCode40**
- Worked on demo card section
 - Fixes code samples removed ceramics
-  Fix List bullet point
-  Test image assets
Resolves #35 #36 #37

### CODE REVIEW

**Comment by nick-verida** [comment]
#35 isn't fixed. 

The issue says:

> Remove the blank image holders

To clarify: we'd like to remove the images altogether, not replace them with something else (the replacement images don't look great).

On http://localhost:8080/connect the title is wrong:

image

Should be "Next Demo"

From the issue:

> Make the whole text work as a link (not just the arrows)

This is partially done, but the "Previous Demo" and "Next Demo" text isn't linked. 

On http://localhost:8080/send-message

image

* The "Previous Demo" arrow should be on the left side, and pointing back (towards the left)
* The "Previous Demo" is "Connect" (not Send Message)
* The Previous demo link is wrong

On http://localhost:8080/store-data

from the issue:

> The final demo should only link to the previous one. The link should be centered on the page

It currently has a "Next Demo" (I did write "only link to the next demo" on the issue. I've corrected that now)

**Comment by nick-verida** [comment]
Issues #36 and #37 look good. 

Can you remove #38 if this doesn't resolve it, and move your comments to that issue please.

**Comment by cmcWebCode40** [comment]
@nick-verida, 

i have made requested changes for this PR,

**Comment by nick-verida** [comment]
Looks a lot better. 

Can we make it so when you press the "Previous" and "Next" links it goes to the top of the page please.

**Review by nick-verida — APPROVED** [review]
Looks good, merging

**Pull request merged**
